> Python tool for filtration of raw Illumina reads - FastQ Filtrator

## Introduction
FastQ Filtrator is a tool for filtering raw Illumina data based on three different parameters:

* GC composition
* Length of the reads
* Average quality of the read

## Installing
To start working with FastQ Filtratot please download fastq_filtrator.py to a chosen folder on the computer.

## Start
To start the tool in your terminal please type the absolute path to the tool script and then print:
'python fastq_filtrator.py'

## Example
You can do a trial run of the tool on a data that is called example.fastq.

## Functions that are presented in the tool:
** fastq_filter
** open_fastq_file
** quality_control
** gc_content_filter
** length_filter
** quality_filter
** saving
** change_of_parameters

## Authors and acknowledgements
#### Main contributor
* Valeriia Ladyhina

## Feedback
 If you have any questions or complains please approach the author of FastQ Filtrator via email:
 'valeriia.ladyhina@gmail.com'
